### ISSUE TITLE
locales() method bug

### ISSUE THREAD

**Issue by aeq-dev** [outer-web/filament-translatable-fields#1]
Hi,
I'm getting this error  : 
`Call to undefined method Outerweb\FilamentTranslatableFields\Filament\Plugins\FilamentTranslatableFieldsPlugin::locales()`

My  Panel  code : 
```
FilamentTranslatableFieldsPlugin::make()
                    ->locales(['en', 'ar', 'fr']),
```

**Comment by SimonBroekaert** [comment]
Hi,

My bad! The README.md file had some wrong information in it.

To add supported locales, use the `supportedLocales` method instead of the `locales` method.


Sorry for the misinformation!
