### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by karam-mustafa** [outer-web/filament-translatable-fields#3]
Hello, I've just installed and run the package on a table and title column
but I got this error message when I was trying to create a new record 

**Illuminate\Database\Grammar::parameterize(): Argument #1 ($values) must be of type array, string given**

package versions; 

- laravel version: 11.1.1
- filament-translatable-fields: 1.1.0
- filament: 3.2.61

The screenshot of the error 
![WhatsApp Image 2024-03-30 at 3 43 15 AM](https://github.com/outer-web/filament-translatable-fields/assets/71431942/f9db7da4-d262-4928-a594-dd2b56222ce0)

**Comment by SimonBroekaert** [comment]
Hello, could you show me your code where you use the `translatable()` method?

Thanks!

**Comment by karam-mustafa** [comment]
Thanks for your reply @SimonBroekaert 

This is my code 

```
  public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('title')
                    ->required()
                    ->maxLength(255)
                    ->translatable(),
                Forms\Components\Textarea::make('description')
                    ->required()
                    ->columnSpanFull(),
                Forms\Components\FileUpload::make('image')
                    ->image()
                    ->required(),
            ]);
    }
```

**Comment by SimonBroekaert** [comment]
Hi @karam-mustafa ,

I was not able to replicate the issue myself.

Could you supply some more information.

Was the value saved to your database or not? What DB engine are u using (Mysql or something else?)

Could you also check if you are using the `protected $casts = ['title' => 'array']` on your model?

Sorry for the late reply, I'm a solo dev with a main job and a side job

**Comment by SimonBroekaert** [comment]
Closing as OP did not answer anymore.

Feel free to open again if needed!

Thanks for using this package!

**Comment by karam-mustafa** [comment]
Hello @SimonBroekaert , thanks for your response, this was helpful, I 've added `protected $casts = ['title' => 'array']` and everything is good now, but I would suggest adding this to the main documentation, because I didn't found it anywhere🙏❤
