### ISSUE TITLE
Issues when writing tests with translatable()

### ISSUE THREAD

**Issue by Geoffry304** [outer-web/filament-translatable-fields#4]
Hey, I am writing tests with pest and I got this error when I try to run the test.  

`Illuminate\View\ViewException: Method Filament\Forms\Components\TextInput::translatable does not exist.`

I think the macro is not loaded in the test environment.

```php
it('can validate form', function () {
    $rules =  [
        'description' => ['required', 'max:255'],
        'code' => ['required', 'max:6'],
        'type' => ['required',Rule::enum(FoodBeverage::class)],
        'vat_id' => ['required', 'exists:vat_codes,id'],
    ];
    livewire(CreateProductGroup::class)
        ->fillForm([
            'description' => '',
            'code' => '',
        ])
        ->call('create')
        ->assertHasFormErrors($rules);
});
```

**Comment by SimonBroekaert** [comment]
Hi @Geoffry304 ,

I personally have not played with tests and Filament together so I am not sure. I currently also don't have my PC with me as I have some vacation.

I see that you (or someone else) also asked this question here: https://www.answeroverflow.com/m/1225039460224204810?

I see that you currently have a solution? I'm not sure if I should change anything in my package for this? I will keep track of the answeroverflow thread too.
